"""Build the dashboard's bundled demo dataset from a GENUINE v2 backend response.

Source: outputs/mlcc_v2/demo_response_with_outcomes.json, produced by posting
outputs/mlcc_v1/demo_early.csv with demo_outcomes.csv to POST /api/v1/screen on
the mlcc-pilot-1.1 bundle. Records are copied verbatim; the only additions are
per-record outcome fields derived from the response's own evaluation section.
Nothing is invented: a missing value stays null.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "outputs" / "mlcc_v2" / "demo_response_with_outcomes.json"
OUT_JS = ROOT / "frontend" / "src" / "lib" / "demoData.js"
TARGET_MIX = {"ENGINEER_REVIEW": 4, "RETEST": 6, "MONITOR": 8}
TOTAL = 64

response = json.loads(SOURCE.read_text(encoding="utf-8"))
records = response["records"]
outcomes = {}
for o in response.get("evaluation", {}).get("outcomes", []):
    outcomes.setdefault((o["component_id"], o["measurement_name"]), []).append(o)

by_decision = {}
for r in records:
    by_decision.setdefault(r["recommendation"], []).append(r)
selected = []
for decision, n in TARGET_MIX.items():
    selected.extend(by_decision.get(decision, [])[:n])
selected.extend(by_decision.get("ACCEPT", [])[: TOTAL - len(selected)])

def enrich(r):
    later = sorted(outcomes.get((r["component_id"], r["measurement_name"]), []), key=lambda o: o["observed_hour"])
    final = next((o for o in later if o["observed_hour"] == r["forecast"]["target_hour"]), None)
    limit = r["limits"]["applicable_limit"]
    return {
        **r,
        "outcome_trajectory": [{"hour": o["observed_hour"], "value": o["observed_value"]} for o in later],
        "observed_168h": None if final is None else final["observed_value"],
        "crossed_applicable_limit": None if final is None else final["crossed_applicable_limit"],
        "within_limit_but_unusual": bool(limit is not None and r["latest_value"] < limit and r["anomaly"]["is_anomaly"]),
    }

enriched = [enrich(r) for r in selected]
selected_ids = {(r["component_id"], r["measurement_name"]) for r in enriched}
counts = {k: 0 for k in ("ACCEPT", "MONITOR", "RETEST", "ENGINEER_REVIEW")}
for r in enriched:
    counts[r["recommendation"]] += 1

dataset = {
    **{k: v for k, v in response.items() if k not in ("records", "unscored_records", "component_summaries", "evaluation", "decision_counts", "_note")},
    "unique_component_count": len(enriched),
    "measurement_record_count": len(enriched),
    "scored_record_count": len(enriched),
    "unscored_record_count": 0,
    "decision_counts": counts,
    "records": enriched,
    "unscored_records": [],
    "component_summaries": [s for s in response.get("component_summaries", []) if any(s["component_id"] == cid for cid, _ in selected_ids)],
    "evaluation": {**response["evaluation"], "outcomes": [o for o in response["evaluation"]["outcomes"] if (o["component_id"], o["measurement_name"]) in selected_ids]},
    "within_limits_but_unusual_count": sum(r["within_limit_but_unusual"] for r in enriched),
    "_note": f"Subset of {len(enriched)} components from a genuine v2 backend response ({SOURCE.name}); records unedited, decision counts recomputed for the subset.",
}
OUT_JS.write_text("// Generated by scripts/build_frontend_fixtures.py from a genuine v2 backend response. Do not hand-edit.\nexport const DEMO_DATASET = " + json.dumps(dataset, indent=2) + ";\n\nexport default DEMO_DATASET;\n", encoding="utf-8")
print(f"wrote {OUT_JS.relative_to(ROOT)}: {len(enriched)} records, counts {counts}, model {dataset['model_info']['selected_model']}, with_outcomes {sum(r['observed_168h'] is not None for r in enriched)}")
